CREATE TABLE club_user (
club_id INTEGER,
user_ID INTEGER,
is_coord BOOLEAN,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (club_id) REFERENCES club(club_id),
FOREIGN KEY (user_ID) REFERENCES user(ID))