CREATE TABLE club(
club_id INT Primary key,
name VARCHAR(20),
description VARChaR(100),
validity_status BOOLEAN,
created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);