# Generated by Django 5.0.2 on 2024-02-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
                ("phone_no", models.TextField()),
                ("email", models.TextField()),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
