# Generated by Django 5.0.2 on 2024-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                ("club_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=400)),
                ("validity_status", models.BooleanField(default=False)),
                ("club_created", models.DateTimeField()),
                ("club_updated", models.DateTimeField()),
            ],
            options={
                "db_table": "club",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ClubUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_coord", models.BooleanField(default=False)),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
            ],
            options={
                "db_table": "club_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=400)),
                ("date", models.DateField(blank=True, null=True)),
                ("time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=30)),
                ("event_created", models.DateTimeField()),
                ("event_updated", models.DateTimeField()),
            ],
            options={
                "db_table": "events",
                "managed": False,
            },
        ),
    ]
