# Generated by Django 5.0.2 on 2024-02-21 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_club_clubuser_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={},
        ),
        migrations.AlterModelOptions(
            name="clubuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="events",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
