# Generated by Django 5.0.2 on 2024-02-21 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_alter_club_options_alter_clubuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubuser",
            name="club",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.club"
            ),
        ),
        migrations.AddField(
            model_name="clubuser",
            name="user",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.DO_NOTHING, to="crm.user"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="club",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.club"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(max_length=10, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=20),
        ),
    ]
