# Generated by Django 5.0.2 on 2024-02-21 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_clubuser_club_clubuser_user_events_club_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="club",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="clubuser",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="events",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
