# Generated by Django 5.0.2 on 2024-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_alter_club_options_alter_clubuser_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField()),
                ("created", models.DateTimeField()),
                ("updated", models.DateTimeField()),
            ],
            options={
                "db_table": "event_user",
                "managed": False,
            },
        ),
    ]
